name = "gleam_contributors"
version = "1.0.0"
licences = ["Apache-2.0"]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.17"
gleam_httpc = "~> 2.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
iso8601 = "~> 1.3"
gleam_erlang = "~> 0.23"
simplifile = "~> 0.1"
gleam_json = "~> 0.7"
envoy = ">= 1.0.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
cymbal = ">= 1.0.0 and < 2.0.0"
gliberapay = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
