name = "gleam_contributors"
version = "1.0.0"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.17"
gleam_httpc = "~> 1.0"
gleam_http = "~> 2.0"
jsone = "~> 1.7"
iso8601 = "~> 1.3"
gleam_erlang = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 0.5"
