name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: "24.2.2"
          gleam-version: "0.25.0"
      - run: gleam test
      - run: gleam format --check src test

